export const JWTOKEN = "JWTOKEN";

// actions:
export const USER_LOGIN_REQUESTED = "USER_LOGIN_REQUESTED";
export const USER_TODOS_AND_QUOTE_FETCH_REQUESTED =
  "USER_TODOS_AND_QUOTE_FETCH_REQUESTED";
